version: "3"

x-logging: &fluent-bit
  driver: fluentd
  options:
    fluentd-address: 172.21.0.6:24224

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    networks:
      - servers
      - monitoring

  reservation-service:
    build: .
    restart: on-failure
    networks:
      - servers
      - monitoring
    environment:
      DATABASE_CONNECTION_STRING: mongodb://user:pass@mongodb:27017
      JAEGER_SERVICE_NAME: user-service
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_MANAGER_HOST_PORT: jaeger:5778
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    ports:
      - "8083:8083"
    logging: *fluent-bit
    depends_on:
      mongodb:
        condition: service_started

networks:
  servers:
    driver: bridge
  monitoring:
    external: true